require('lsp/go-lsp')
require('lsp/lua-lsp')
require('lsp/python-lsp')
require('lsp/typescript-lsp')
require('lsp/vue-lsp')
require('lsp/svelte-lsp')
-- require('lsp/java-lsp.lua')
require('lsp/rust-analyzer')
